application: unset
version: 22-7
runtime: python27       # Which runtime to use.
api_version: 1          # Which version of the API to use for that runtime.
threadsafe: true        # Whether or not to enable threading.
instance_class: F4      # Instance size to handle front-end requests.
default_expiration: 30d

# Third party libraries loaded from the App Engine environment.
libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.1"

builtins:
- remote_api: on
- appstats: on

# Dispatch table from URL -> application instance or from URL -> static content.
handlers:

# Upload static scripts and HTML templates
- url: /static
  static_dir: client
  login: required

# Use version number as part of static file URLs so that long expiration times
# will not affect changes in new deployments.  This is accomplished by the
# handler providing a template variable static_dir, see
# _RequestHandler.RenderHtml in perfkit.explorer.handlers.base.
- url: /_static/.+?/(.*)
  static_files: client/\1
  upload: client/(.*)
  secure: always

# Provides interactive console for debugging purposes in production.
# This is equivalent to /_ah/admin in dev_app_server.
- url: /_ah/dev_console(/.*)?
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

# URLs from /dashboard/* allow consumers to view, create and edit dashboards.
- url: /dashboard/.*
  script: perfkit.explorer.handlers.dashboard.app
  login: required
  secure: always

# URLs from /config are used to get and update the global config.
- url: /config
  script: perfkit.explorer.handlers.explorer_config.app
  login: admin
  secure: always

# URLs from /data/* are Data Providers, and return data in Json format.  This
# is used by the Explorer Pages (mapped below), and can also be used by
# external consumers.
- url: /data/.*
  script: perfkit.explorer.handlers.data.app
  login: required
  secure: always

# URLs from /* are Explorer Pages, and return data in HTML format.
# These pages rely in async calls to the Data Provider (noted above) to provide
# full functionality.
- url: /.*
  script: perfkit.explorer.handlers.pages.app
  login: required
  secure: always

################################################################################
# Generated by app_impl.py.  Do not modify manually.  To disable and manage
# skip_files yourself, pass the --norewrite_app_yaml flag via app.sh or the
# command line.  See go/appsh.
################################################################################
skip_files:
# Default patterns skipped by App Engine, which must be repeated since
# specifying skip_files overrides them otherwise.  See
# https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
# Files produced by blaze that have no effect in App Engine's runtime.
- ^.*\.so$
- ^.*pywrap.+\.py$
- ^.*\.jslib$
- ^.*\.CMF$
- ^.*\.MF$
